# GitHub Copilot Coding Agent セットアップステップ
# このファイルは、Copilot coding agentがビルド環境で実行する初期化ステップを定義します

name: Copilot Setup Steps

# 日本語フォント（Noto CJK）のインストール
# スクリーンショット撮影時に日本語テキストが正しく表示されるようにするため
# 豆腐（□□□）の表示を防ぐために必要です
steps:
  - name: 日本語フォント（Noto CJK）のインストール
    run: |
      echo "日本語フォント（Noto CJK）をインストールしています..."
      sudo apt-get update -qq
      sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
      echo "フォントキャッシュを更新しています..."
      fc-cache -fv
      echo "日本語フォントのインストールが完了しました。"
      echo "インストール済みのNoto CJKフォント:"
      fc-list | grep -i noto | grep -i cjk | head -5
